jwt-user:
  keys:
    access-token-key: '{"kty":"oct","k":"h4dfgRX5ZRZooHem3mEnctZ-KtR9FoESgCnH-3BNgde8"}'
    refresh-token-key: '{"kty":"oct","k":"95dfNwiBe7vR5KnbguLr5irJD-a2gesF"}'
  ttl:
    access-ttl: 20 #Minutes
    refresh-ttl: 1 #Hours
