app:
  gateway:
    api-prefix: /api/v1
    rate-limiter:
      replenish: 8
      burst: 120
      requested: 1
  registration:
    max-confirmation-time: 10m
    confirmation-link-prefix: "http://taskzone.ru/registration-confirm?confirmationId=%s"
  frontend:
    origin: "http://taskzone.ru"    

discovery-service-user:
  server:
    hostname: discovery-service #config-server-property
    port: 8015 #config-server-property

jwt-user:
  keys:
    access-token-key: '{cipher}0f121150425eeebac91aeb2ffeae53268f2896871c8be7a45851cebcd6bbbda732d5212b6c6b6bf0c5454b81f75a40f8cb133904bb74811365e33c0404cbb014411fe3ce591fa83b2b92c702f5e7b98f8909102ab6bd9bea39276a65d4c2c26d'
    refresh-token-key: '{cipher}e546fa4bc44276cb5ba7555425e2663306c7051f8aadbe540800f40ef0632fe95ca5f9fd4c74025fa87af47cb0ccd58eb1d3a933e69c758658fc903852a438a2087cf670bfd5874b64c9aedb7e9a73af'
  ttl:
    access-ttl: 10m #Minutes
    refresh-ttl: 30d #Hours

redis-user:
  host: redis
  port: 6379

kafka-user:
  bootstrap-servers: broker-1:19092,broker-2:19092,broker-3:19092
